name: Ping Supabase to Prevent Pausing

on:
  schedule:
    - cron: '0 9 * * *' # Runs at 9:00 AM UTC every day
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Supabase Client
        run: npm install @supabase/supabase-js --force

      - name: Ping Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          node -e "
          const { createClient } = require('@supabase/supabase-js');
          const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);
          (async () => {
            const { error } = await supabase
              .from('_health')
              .insert({ pinged_at: new Date().toISOString() });
            if (error) {
              console.error('Error inserting into _health table:', error);
              process.exit(1);
            } else {
              console.log('Successfully pinged _health table.');
            }
          })();
          "
